#!/bin/bash
#check file names before running
#if you do not have your original hosts file named /etc/hosts.bk script will exit.
#if a file named /etc/hosts.temp already exists script will exit
#amount of time measured in seconds for the hosts to be allowed
seconds=300

if [ -e /etc/hosts.bk ]
then
    echo "Do nothing" > /dev/null
     else
cat << EOF > /tmp/hosts.bk
127.0.0.1       localhost
127.0.1.1       afasfkjbasfasf

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
sed -i s/afasfkjbasfasf/`hostname`/g /tmp/hosts.bk && sudo mv /tmp/hosts.bk /etc/hosts.bk
fi

if [ -e /etc/hosts.temp ]
then
    echo "hosts already unblocked" && exit
     else
    echo "Do nothing" > /dev/null
fi
sudo mv /etc/hosts /etc/hosts.temp
sudo cp /etc/hosts.bk /etc/hosts
echo "hosts unblocked for 5 minutes"
sleep $seconds && sudo mv /etc/hosts.temp /etc/hosts&
